// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCgi00oV63PJRe8WQOEQhMImEa2pvwq2nA',
    appId: '1:186683168365:web:8f29f19f779d42f567d164',
    messagingSenderId: '186683168365',
    projectId: 'pizzaqdeliveryproject',
    authDomain: 'pizzaqdeliveryproject.firebaseapp.com',
    storageBucket: 'pizzaqdeliveryproject.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-C3L5S96Gu6Z9nb2zZqwp-7fYaaUjY0s',
    appId: '1:186683168365:android:0f4623f906ef998967d164',
    messagingSenderId: '186683168365',
    projectId: 'pizzaqdeliveryproject',
    storageBucket: 'pizzaqdeliveryproject.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAgykeWhmyLUkQiAbaZNgO8K3zY4P0kIrk',
    appId: '1:186683168365:ios:a619e1f2ca5302b867d164',
    messagingSenderId: '186683168365',
    projectId: 'pizzaqdeliveryproject',
    storageBucket: 'pizzaqdeliveryproject.appspot.com',
    iosBundleId: 'com.pappagpizza.PappaGeorggeoPizza',
  );
}
